### ISSUE TITLE
Spin resonance strength calc is not using consistent spin tune

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#1047]
Sum and difference resonances can be switched in Tao's `show spin` output.

**Comment by DavidSagan** [comment]
Fixed.

**Comment by eiad-hamwi** [comment]
In the following lattice file, the usual convention should produce a sum resonance, but it appears as a difference resonance instead.

[ags_flattop_res.zip](https://github.com/user-attachments/files/16274825/ags_flattop_res.zip)

The correct resonance strength is the smaller value, since I'd already optimized the skew-quadrupoles (QSHRES*) against it.

**Comment by DavidSagan** [comment]
Everything fixed.
