### ISSUE TITLE
`curve(1)%data_type   = 'spin_dn_dpz.x'` gives error

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1292]
**Describe the bug**
```
[MESSAGE | 2024-NOV-14 16:30:59] tao_init:
    OpenMP active with number of threads: 24
[ERROR | 2024-NOV-14 16:31:00] tao_set_curve_invalid:
    INVALID DATA_TYPE: "spin_dn_dpz.x"
    FOR CURVE: dn_ddelta.d.c1
[ERROR | 2024-NOV-14 16:31:00] tao_set_curve_invalid:
    INVALID DATA_TYPE: "spin_dn_dpz.y"
    FOR CURVE: dn_ddelta.d.c2
[ERROR | 2024-NOV-14 16:31:00] tao_set_curve_invalid:
    INVALID DATA_TYPE: "spin_dn_dpz.z"
    FOR CURVE: dn_ddelta.d.c3
```

**Minimal Working Example**
Run tao. Try `place r00 spin_dn_dpz` and youll see suddenly the graph works and the data type for the curves is `spin_dn_dpz.x` etc.

**Comment by DavidSagan** [comment]
@mattsignorelli Can you attach example input files? Thanks.

**Comment by mattsignorelli** [comment]
Sorry I thought I attached them. they're below now
[Archive.zip](https://github.com/user-attachments/files/17803436/Archive.zip)

**Comment by DavidSagan** [comment]
Fixed. The issue was actually that the plotting was trying to do a "smooth line" calculation where the datum is evaluated within lattice elements. However, this type of datum was not setup with the ability to evaluate at arbitrary positions. And since evaluate everywhere would be very slow, the solution was to turn off the smooth line calc for this type of datum.
