### ISSUE TITLE
Intel Fortran libraries incorrectly added when using gfortran+OpenMPI

### ISSUE THREAD

**Issue by mattgibbs** [bmad-sim/bmad-ecosystem#141]
In build_system/Master.cmake:

When `${ACC_ENABLE_MPI}` is true, the `CMAKE_Fortran_COMPILER` variable is set to 'mpifort'.  Later on in the script, there are statements that use `${CMAKE_Fortran_COMPILER} MATCHES "ifort"` to determine if the Intel Fortran compiler is being used.  This evaluates to true for 'mpifort', so a bunch of Intel-specific libraries are added to the linker list, even though we aren't using an Intel compiler.  This breaks the build.

Using 'STREQUAL' instead of 'MATCHES' fixes the problem.  I've attached a modified version of Master.cmake that includes the fix.

Update: The initial file I attached was incorrect.  I've fixed that, use this one instead!)
[Master.cmake.txt](https://github.com/DavidSagan/Bmad/files/2798174/Master.cmake.txt)

**Comment by DavidSagan** [comment]
@mattgibbs @attiliodefalco Hi Matt: Attilio De Falco is the person who handles script issues and he will be looking at this and the other problem come Monday.  -- Cheers, David

**Comment by attiliodefalco** [comment]
Hi Matt,

I'm still working on the two issues.

The solution for using the local OpenMPI is to remove version checking and only build when OpenMPI is not present.  The gfortran mpifort issue seems to be fixed with your suggested edits.  Will be testing all this tomorrow and Wednesday againt our build system.

Thanks,

~Attilio





On Jan 25, 2019, at 9:37 PM, David Sagan <notifications@github.com<mailto:notifications@github.com>> wrote:


@mattgibbs<https://github.com/mattgibbs> @attiliodefalco<https://github.com/attiliodefalco> Hi Matt: Attilio De Falco is the person who handles script issues and he will be looking at this and the other problem come Monday. -- Cheers, David

**Comment by mattgibbs** [comment]
Thanks @attiliodefalco and @DavidSagan.  Let me know if you'd like help testing the fix.

**Comment by attiliodefalco** [comment]
Hi Matt,

The issues you found have been fixed, using your suggestions.

Using the local OpenMPI is now set via setting both ACC_ENABLE_MPI="Y" and ACC_FORCE_BUILTIN_MPI="Y" in dist_prefs, if the local version is lower than the Distribution source version.  As well, build when OpenMPI is not present, when ACC_ENABLE_MPI="Y" is set.  The C/C++ and Fortran compilers used to build the local OpenMPI must be the same as for building the Distribution.

The Master.cmake was also updated as you suggested.

Thanks for pointing out these issues!

~Attilio





On Jan 25, 2019, at 9:37 PM, David Sagan <notifications@github.com<mailto:notifications@github.com>> wrote:


@mattgibbs<https://github.com/mattgibbs> @attiliodefalco<https://github.com/attiliodefalco> Hi Matt: Attilio De Falco is the person who handles script issues and he will be looking at this and the other problem come Monday. -- Cheers, David

**Comment by attiliodefalco** [comment]
This issue can be closed.  ~Attilio
