### ISSUE TITLE
Documentation cleanup: section 10.4 (Lattice Initialization)

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#211]
In the Lattice Initialization section of the documentation, there are a couple of unused/unexplained items:
- In the `tao_design_lattice` namelist, what does `common_lattice` do?
- Just after that there is a reference to "the possible common universe created when using CRL analysis," the latter phrase being undefined and not coming up when searching.

**Comment by DavidSagan** [comment]
The common lattice was implemented a long time ago to do orbit response matrix analysis. The problem was that with a large machine where there could be hundreds of orbits taken (one for each steering), if there was one universe created for each orbit this could overload Tao. This feature was never used and has fallen into disrepair. In light of the fact that it was a big maintenance headache, I removed the common lattice code. I will go through and do some more cleanup...

**Comment by DavidSagan** [comment]
Done.
