### ISSUE TITLE
New long term tracking bug - emittances go to 0 when split_bends = T

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#287]
Radiation damping and fluctuations are on.  I did not see the same issue when having split_bends_for_stochastic_rad = F. Input files are attached.
[bug.zip](https://github.com/DavidSagan/Bmad/files/9998068/bug.zip)

**Comment by mattsignorelli** [comment]
This is seen in map tracking (1st, 2nd, 3rd order) and Bmad tracking methods. I have not tested PTC

**Comment by DavidSagan** [comment]
@mattsignorelli Problem is that to avoid a bug involving the case of an element's name, the case of an element's name is now automatically uppercased by the add_superimpose routine. The change happened October 7. This conflicted with the bend splitting in long_term_tracking which was using a mixed case name for the markers that were inserted. Now the marker names are uppercased and the problem is fixed.
