### ISSUE TITLE
ltt program gives negative time after 0th turn

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#307]
The averages output file looks like this:
##   Turn   N_live          Time  Polarization          <Sx>          <Sy>          <Sz>             <x>          <px>           <y>          <py>           <z>          <pz>          <pc>         <p0c>           Sig_x        Sig_px         Sig_y        Sig_py         Sig_z        Sig_pz
        0      500 -8.536504E-25   0.000000000     0.000000000   0.000000000   0.000000000   -5.842628E-09 -5.360040E-10 -2.604626E-23 -8.682088E-24  1.314504E-16  2.645453E-20  3.917560E+12  3.917560E+12    2.114113E-05  1.541532E-05  1.174235E-06  2.337201E-07  8.400000E+00  2.000000E-03
        1        0 -1.000000E+00   0.000000000     0.000000000   0.000000000   0.000000000    2.000000E+03 -3.437191E-06  4.580466E-06  4.662090E-07 -6.272590E+00 -3.812034E-04  3.916067E+12  3.917560E+12    0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00
[error.zip](https://github.com/DavidSagan/Bmad/files/10230293/error.zip)

**Comment by DavidSagan** [comment]
@henrylovelace3 With zero live particles, no average time can be calculated so any number here is meaningless. What is strange is that the program should detect that there are no live particles before trying to print anything. And indeed that is what happens when I run it (both the single threaded and MPI versions).
