### ISSUE TITLE
Lattice instability with beambeam

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#367]
I have a lattice file file which is stable, and when I add a certain beambeam element it becomes unstable. The beambeam element should not be strong enough to make the lattice unstable, and I checked on my own with the matrices, and I get a stable result. I also found that if I turned off the beambeam and then turned it back on, it would find a stable solution. The file is: /nfs/acc/temp/jeu8/solenoid/5.6/2IP/solenoid_correction/sol_cor_only_IP8_v3_bb.bmad

**Comment by DavidSagan** [comment]
Tao is calculating that with the beambeam element on the lattice is unstable. Do you get the same 1-turn matrix as Tao with the beambeam element on? The behavior you see with turning the beambeam element off and on is due to the match elements where, when you turn the beambeam element off, the match elements can set their matrices (the matrices defaulted to the unit matrix initially) and then when the beambeam is switched on, the lattice is not in the same state as it was initially.

**Comment by jeu8** [comment]
I think I might see where my issue is coming from. 

If I make a lattice that includes phase trombones and want to see what happens with a beambeam interaction, I suppose it is incorrect to put a beambeam in the lattice file and run it, because the matrices from the phase trombones will no longer be the same. Would the correct way be to set the matrices manually or turn on the beambeam once the lattice is being run and the trombones are set?

**Comment by DavidSagan** [comment]
I would recommend the following:

1. Set the beambeam element off.
2. Read the lattice into Tao which will set the match elements appropriately.
3. Write a bmad lattice file. 
4. Copy the match elements from the written file into your original file (or just use the written file) and set phase_trombone = F to prevent alteration of the Twiss parameters.
5. Now you can use this lattice file and not worry about match elements changing.

I am closing this Issue but you can always reply if you have more questions.
