### ISSUE TITLE
A question on Touschek_background

### ISSUE THREAD

**Issue by Kulibo-lv12** [bmad-sim/bmad-ecosystem#368]
After running mpi -np 4  touschek_background  touschek_background.in with my lattice file , there is no particle produced. I find out that perhaps there is  somthing wrong with calling touschek_rate1(...,mode,...).  mode%sig_p and mode%sig_z haven't been calculated because radiation_integral returns dummy_mode instead of mode before calling touschek_rate1(...,mode,...) 
[files.zip](https://github.com/DavidSagan/Bmad/files/11010082/files.zip)

**Comment by DavidSagan** [comment]
@Kulibo-lv12 pz_aperture_by_s.out is missing and the program cannot be run without it.

**Comment by Kulibo-lv12** [comment]
@DavidSagan  I add pz_aperture_by_s.out to files1.zip now.
[files1.zip](https://github.com/DavidSagan/Bmad/files/11024596/files1.zip)

**Comment by DavidSagan** [comment]
Bug reported to Michael Ehrlichman.

**Comment by MichaelEhrlichman** [comment]
@Kulibo-lv12 The code touschek_backgrount was originally developed for open geometries (linacs like Cornell's ERL).  The problem you are encountering is because in linacs, energy spread is element-by-element and so the code gets the energy spread from the element struct.  In closed geometries like rings, energy spread is nominally constant and typically obtained from the mode struct.

The above mentioned energy spread problem could be fixed easily enough.  However, further development would be required to develop and vet touschek_background on storage rings.

Would you like to collaborate on this?  I could fix the energy spread problem and any other obvious problems with running the code on storage rings.  Your task would be to test the code on your ring and make sure the results make sense.

The results could end up being a nice conference proceeding.

**Comment by Kulibo-lv12** [comment]
@MichaelEhrlichman  Ok, I'm willing to help to test touschek_background with my storage ring lattice if you can fix problems in the program.

**Comment by MichaelEhrlichman** [comment]
@Kulibo-lv12 OK, good.  Are you on the Bmad Slack channel?  Here is an invite link.

https://join.slack.com/t/bmad-simulation/shared_invite/zt-1u3868g5e-B1WSLhDm5FL7PMtGlzBRXw

**Comment by Kulibo-lv12** [comment]
@MichaelEhrlichman  Yeah, I'm on the Bmad Slack channel. At first, I reported this problem on Slack. I also reported that there was a problem in aperture_by_tracking and you fixed that problem two months ago. Perhaps you forget it. My username  on Slack  is Hongjin Fu.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Can this issue be closed?

**Comment by MichaelEhrlichman** [comment]
Touschek background was modified to support rings and tested OK for Kulibo-lvl12's case.  I would say this issue can be closed.  However, the "this code has not been extensively tested and results should be considered carefully" message in touschek_background should remain for now.
