### ISSUE TITLE
superimposed sextupole issue

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#463]
I am using superimposed sextupoles in a lattice, and there appears to be an issue with how Tao is treating them. They do not effect the chromaticity and crash Tao when I attempt to plot dphi.

**Comment by jeu8** [comment]
files are at /nfs/acc/temp/jeu8/test

**Comment by DavidSagan** [comment]
@jeu8 The superimposed sextupoles do indeed affect the chromaticity. I suspect that the problem you are having is that the sextupoles cannot be varied directly since the k2 parameter of the sextupoles is controlled by an overly.

The plotting problem was due to the chromaticity calc failing due to failure to find a closed off-energy orbit. I have put in code to print a warning and code to prevent the crash in this case.

**Comment by jeu8** [comment]
The plotting issue is fixed. I removed the superimposed sextupoles from the array so I can vary them separately. I set the k2 value of all of the SFC sextupoles to varying large values (both positive and negative) and saw no change in the chromaticity

**Comment by jeu8** [comment]
I discovered the issue. I had not yet changed the sextupole strengths when I added the new superimposed sextupoles, this meant that new combined strength over compensated the chromaticity so much that it broke Tao. If I set the strengths to zero and re-optimized, the issue goes away
