### ISSUE TITLE
setting downstream lcavity affects beginning p0c

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#488]
This lattice has an `e_gun`, `drift`, and `cavity` in order. Setting the cavity phase affects the upstream p0c!

```
tao -lat lat.bmad -noplot -command "sho value ele::beginning[p0c];set ele cav phi0 = 0.25;sho value ele::beginning[p0c];quit"

Tao: sho value ele::beginning[p0c]
     7.5418779658641934E+05

Tao: set ele cav phi0 = 0.25

Tao: sho value ele::beginning[p0c]
     7.5418774768068851E+05

```

Input files are in my CLASSE error directory, `tao_set_downstream_affects_upstream`

**Comment by DavidSagan** [comment]
Looks like bmad-sim/bmad-ecosystem#487.

**Comment by ChristopherMayes** [comment]
How is this related to runge-kutta? Setting a downstream element shouldn't have affected the upstream element. 

```
Tao> sho lat
# Values shown are for the Exit End of each Element:
# Index name   key            s    l  beta  phi_a  eta  orbit  beta  phi_b  eta  orbit Track
#                              a  [2pi]   x x [mm]    b  [2pi]   y y [mm] State
   0 BEGINNING Beginning_Ele     0.000   ---  10.00  0.000  0.00  0.000  10.00  0.000  0.00  0.000 Alive
   1 GUN    E_Gun         0.150  0.150  2.03  0.009  0.00  0.000  2.03  0.009  0.00  0.000 Alive
   2 D1    Drift         0.250  0.100  0.91  0.021  0.00  0.000  0.91  0.021  0.00  0.000 Alive
   3 CAV    Lcavity        1.250  1.000  14.50  0.478  0.00  0.000  14.50  0.478  0.00  0.000 Alive
   4 END    Marker        1.250  0.000  14.50  0.478  0.00  0.000  14.50  0.478  0.00  0.000 Alive
# Index name   key            s    l  beta  phi_a  eta  orbit  beta  phi_b  eta  orbit Track

```

**Comment by ChristopherMayes** [comment]
Tightening the adaptive tracking tolerances by a factor of 10,000 moves the differences down a few decimals:
```
bmad_com[rel_tol_adaptive_tracking] = 1e-8  * 1e-4
bmad_com[abs_tol_adaptive_tracking] = 1e-10 * 1e-4
```

```
Tao: sho value ele::beginning[p0c]
     7.5418774851624970E+05

Tao: set ele cav phi0 = 0.25

Tao: sho value ele::beginning[p0c]
     7.5418774853115005E+05
```

**Comment by DavidSagan** [comment]
If the tracking method is set to `fixed_step_time_runge_kutta` the problem goes away. This shows that problem is dues to the adaptive step control. The fundamental problem is that the reference energy is used in the step size calculation so there is a chicken and egg circular dependency which is intrinsic to time_runge_kutta. 

The setting of `phi0` just triggers a ref energy recalc. I have modified the code so that in this case a recalc is not triggered but be aware that this just lessens where the issue will be seen and is in no way a "fix".
