### ISSUE TITLE
Optimizing with emittance datum

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#550]
Run lm with the attached files  - strange behavior and unable to change emittance at all
[esr-nogroup.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12834602/esr-nogroup.zip)

**Comment by mattsignorelli** [comment]
Also get same result when using less variables - for example only vkickers[34] and hkickers[34:36], and a new nonzero closed orbit appears after optimizing even though all the kickers strengths are unchanged after running lm

**Comment by mattsignorelli** [comment]
This is actually occurring with a spin datum now as well. There seems to be something about this particular lattice

**Comment by DavidSagan** [comment]
The major problem here is that the emit datum target (`meas`) value is 2 so the contribution to the merit function (`model - meas`) changes very little. I checked and the emittance does change.

One issue I noticed is that the emit datum was using the radiation integrals emit value instead of the more modern 6D value. I have modified the code to use the 6D value.
