### ISSUE TITLE
Crab cavity transfer matrix 

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#563]
The transfer matrix values (m25, m61) I get do correspond to Eq 4.16 in the Bmad manual, however shouldn't there be a length dependence rather than just voltage for these quantities (i.e. V*L)?

**Comment by DavidSagan** [comment]
@mattsignorelli The dependency is grad*L not V*L. And notice that Eq 4.16 is for a "thin crab cavity" (text before eq 4.14). If you find this answer sufficient, please close the Issue.

**Comment by mattsignorelli** [comment]
I am using a thick crab cavity (L=0.52) and am still seeing no dependence on length, is that correct?

**Comment by DavidSagan** [comment]
How many steps are you using?

**Comment by mattsignorelli** [comment]
10 was the default, upping it to 52 makes no difference

**Comment by DavidSagan** [comment]
I will look into it...

**Comment by DavidSagan** [comment]
@mattsignorelli There will be very little length dependence since Bmad is essentially assuming a traveling wave cavity. Note: PTC's model is different from Bmad's  and with PTC there is variation of M56 but not with M25. Both PTC and Bmad tracking are symplectic so unless you know how the actual cavity is constructed, there is no reason to prefer one over the other.
