### ISSUE TITLE
`show spin` affects orbital 1-turn matrix

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#629]
When asking Tao `show spin -ele 0 -g` to print the 1-turn 8x8 matrix, it seems like the orbital part of that calculation is distinct from the `show mat` calculation. 

It seems the difference stems from the `spin_concat_linear_maps.f90` routine for calculation of the orbital map, as opposed to `transfer_matrix_calc.f90` which just concatenates the `ele%mat6` of consecutive elements.

Interestingly, if you `set ele * spin_tracking_method = sprint` before the first call to `show spin -e 0 -g`, then this issue is avoided. However, if you first show spin, then change the spin_tracking_method then the issue will occur. 

Try the following lattice for instance:
[hsr.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13302796/hsr.zip)

**Comment by eiad-hamwi** [comment]
Note: spin calculations are more significantly affected by this. 
Resonance strength calculations can be more than 15% different between the 2 spin tracking methods, which I believe is an artefact of this issue rather than an error in spin tracking.

**Comment by DavidSagan** [comment]
@eiad-hamwi The issue is that `spin_concat_linear_maps` use PTC for the calculation while `show mat` uses Bmad (if you have not changed the tracking_method). It is possible that differences may be minimized by varying step lengths. However, fundamentally there is no way to totally eliminate the differences.
