### ISSUE TITLE
timing or frequency issue for rf with cartesian maps

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#657]
I am working on getting the frequency correct for a lattice with a nonzero orbit due to the cartesian map wiggler. My rf frequency should be f=h/T_rev, however I cannot get a stable lattice with rf using this. I am getting T_rev by looking at the end element and taking t_particle. Is this the correct time to use? I also adjusted the phase to fix the timing issue, which appears to be working so I am guessing my frequency is still off. 
[cooler.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13506573/cooler.zip)

**Comment by DavidSagan** [comment]
@jeu8 The closed orbit calculation with relative time tracking (the default) is not affected by the RF frequency. Rather, the calculation tries to find the orbit with z(end) = z(beginning). To get what you want you can either 1) put in a time patch to make the closed orbit revolution frequency without RF equal to a harmonic of the zero orbit or 2) switch to `parameter[absolute_time_tracking] = T`.

The second option can complicate things if there are multiple cavities since then you would be responsible for making sure the phasing between cavities is correct. But in your case there is only one cavity so you do not have to worry about this. Notice that adjusting the RF phase only changes the overall z-position of the closed orbit but otherwise does not affect the closed orbit.
