### ISSUE TITLE
Issues about center floor coordinate and particle species with foil

### ISSUE THREAD

**Issue by wlin6927** [bmad-sim/bmad-ecosystem#709]
Several problems encountered while constructing the injection line:

1. 'show lat -branch 1 -center -floor' doesn't work properly, the floor coordinates at element centers are not shown in the second branch

2. Error encountered when injecting H- into second branch with a foil:
    [ABORT | 2023-DEC-20 13:01:28] charge_of:
    CHARGE NOT KNOWN FOR SPECIES: -999

All relative files are attached, main file to run is ltb.run.bmad, where branches and geometry are defined.

[ltb_lattice.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13730709/ltb_lattice.zip)

**Comment by DavidSagan** [comment]
1. The `show lat` problem was due to a problem with not being able to calculate a closed orbit. The orbit calculation problem was due to the fact that the foil element was introducing random scattering. To get around this, I have introduced a `scatter` parameter to foil elements which can be used to turn off scattering.
2. The `CHARGE NOT KNOWN` problem was due to Bmad trying to compute radiation integrals using an initialized orbit (since the closed orbit was not being calculated). This has been fixed.
