### ISSUE TITLE
Orbit Plot Problem With Crab Cavity and Patch Elements

### ISSUE THREAD

**Issue by electronsandstuff** [bmad-sim/bmad-ecosystem#767]
I have created a lattice using a crab cavity to kick a beam and then a patch elements to recenter the orbit. When I do this I observe the plotted orbit being different from what is shown in tao.

Here is a screenshot of the orbit.
![tao screenshot](https://github.com/bmad-sim/bmad-ecosystem/assets/61094787/124959e3-7fae-439d-963c-60f1bb5737e3)

Here is what tao says it should be.
```
Tao> sho orbit end
x  -9.98564752E-08
px -2.11664576E-08
y   4.37520892E-05
py  1.04169902E-05
z  -9.66031187E-04
pz  5.82061664E-09
```

I have prepared a minimal example which is at `/nfs/acc/temp/cmp285/bmad_issues/plotting_issue` on the CLASSE filesystem if someone wants to take a look.

**Comment by electronsandstuff** [comment]
While messing around with another issue I am running into, I discovered that you can make the problem even more severe by turning on absolute time tracking.

I added the following line to `plotting_problem.bmad` on line 13.
```
bmad_com[absolute_time_tracking] = T
```

Here is the plot.
![tao screenshot](https://github.com/bmad-sim/bmad-ecosystem/assets/61094787/a298549c-8ec4-46ca-8549-ec62ec6c37c2)

Here is what tao says the orbit should be.
```
Tao: sho orbit end
x  -9.98564752E-08
px -2.11664576E-08
y   4.37520892E-05
py  1.04169902E-05
z  -9.66031187E-04
pz  5.82061664E-09
```

The dispersion also seems to be plotted wrong here. Tao reports the following.
```
Tao: sho ele end
...
Eta (m)         -2.50726776    -0.00003900
```

**Comment by DavidSagan** [comment]
Problem is that element KCK05 has such a strong kick that the default number of steps (which is 1) gives a notable inaccuracy. The solution is to increase num_steps for this element (or decrease ds_step). This problem happens all the time since it is not possible for Bmad to calculate what the number of steps should be. Next time you see a difference between plotting (which typically is using more steps to get a smooth curve) and what you see with `show ele` or `show lat` start varying step sizes to see if that is the problem.
